name: Missional Communities
favicon: null
layout_spectrum: 0
typography_spectrum: 0.3604310934897512
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.8446264348458499
  lightness: 0.7387037929147482
  saturation: 0.31937993154861033
  rhythmicContrast: 0.6695034655276686
purpose: []
